# User config
title: 경본
subtitle: 블로그!
author: "Bon"
tagline: "Pineapple Certfied Jekyll Theme"
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "watchbon@kakao.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/99kb/"

# Site config
url: "https://99kb.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
